baseURL = "https://packslip.dev/"
locale = "en-US"
title = "packslip"
disableKinds = ["rss", "sitemap", "taxonomy", "term"]

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
  [markup.highlight]
    noClasses = false
